# Site
name: "woojimarket"
title: "woojimarket"
description: "당신의 품격을 올려주는 '우지마켓'입니다."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /woojimarket
google_analytics: 'UA-157553034-1'
disqus: 'woojimarket'  # 페북, 트위터 아이디?
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'  # 여기는 어떤 주소?
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Woo:
    name: Woo
    display_name: Woo
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: woojimarket@gmail.com
    web: 
    facebook: https://www.facebook.com/woojimarket
    description: "Author of Woojimarket"
  john:
    name: Ji
    display_name: Ji
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: woojidream@gmail.com
    web: 
    facebook: https://www.facebook.com/woojimarket
    description: "Author of Woojimarket"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
